version: '2'

volumes:
  piwik-data:
  piwik-mariadb:

services:
  piwik-php-fpm:
    image: aknaebel/piwik
    links:
      - piwik-db
    volumes:
      - piwik-data:/var/www/piwik
    restart: always

  piwik-db:
    image: mariadb:10.3
    volumes:
      - piwik-mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SUPER_STRONG_PASSWORD # TODO: change me
    restart: always

  nginx-front:
    image: alpine:3.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
    restart: always
    command: |
      sh -c "apk add --update nginx ; mkdir -pv /run/nginx && ln -svf /dev/stdout /var/log/nginx/access.log && ln -svf /dev/stderr /var/log/nginx/error.log && exec nginx -g 'daemon off;'"
    volumes:
      - "./nginx-conf.d:/etc/nginx/conf.d:ro"
      - piwik-data:/var/www/piwik:ro
    links:
      - piwik-php-fpm
