FROM alpine:3.19
MAINTAINER Wang Guan <momocraft@gmail.com>

# NO npm or other package manager: this image is meant to run (bundled or packaged) scripts
RUN apk add --update --no-cache chromium nodejs font-noto font-noto-cjk font-noto-cjk-extra
