#!/bin/sh
# exec caddy_linux_amd64 -ca "https://acme-staging.api.letsencrypt.org/directory" -email "noemail@example.com" -conf /etc/Caddyfile -agree
exec caddy -ca "https://acme-staging.api.letsencrypt.org/directory" -email "noemail@example.com" -conf /etc/Caddyfile -agree
